version: '3'

services:
  backend:
    restart: unless-stopped
    container_name: belayer-backend
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}